sudo: required
services: 
 - docker
 
before_install:
 - docker build -t coolshaddy/react-test -f ./Dockerfile.dev .


script:
 - docker run coolshaddy/react-test npm test -- --coverage 


after_success:
 - docker build -t coolshaddy81/custom_client . 

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 - docker push coolshaddy81/custom_client


deploy:
 provider: elasticbeanstalk
 edge: true
 region: eu-west-1
 app: myapp
 env: Myapp-env
 bucket_name: elasticbeanstalk-eu-west-1-955387369960
 bucket_path: myapp
 on:
  branch: master
 
 access_key_id: $AWS_ACCESS_KEY  
 secret_access_key: $AWS_SECRET_KEY     

